SNOW_USER = "APP_STREAMLIT_STAGING"
SNOW_PASSWORD = "EMCsOZmjE6Pc/cIc216ZmJvK0pky6GakeereXcZb/r7WcDO/oJxyvbAM"
SNOW_ACCOUNT = "ak29851.eu-west-1"
SNOW_ROLE = "STAGING.APP_STREAMLIT"
SNOW_WAREHOUSE= "STAGING_APP_ADMIN_MARKETPARTS"

#for view
SNOW_DATABASE = "STAGING_APP"
SNOW_SCHEMA = "COR"
